basePath_upload: "unknow"
basePath_preview: "unknow"
max_size: 100000000
type_reg: "pptx?|docx?|pdf"
spring:
  mail:
    host: smtp.163.com
    password: forxkasake78647
    default-encoding: utf-8
    protocol: smtp
    port: 465
  datasource:
    url: jdbc:mysql://211.87.227.234:3306/zhiku?characterEncoding=utf-8
    username: root
    password: Zhiku_123
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix:
      suffix: .html
mybatis:
  type-aliases-package: com.zhiku.entity
  mapper-locations: com/zhiku/mapper/*.xml
server:
  port: 80
logging:
  level:
    com.zhiku.*: debug